"""Price-change event: a single listing's price moved between two dates.

Generated by diffing snapshots; not stored as a first-class table (the
snapshot history is the source of truth, and recomputing is cheap).
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from alc_crawler.domain.value_objects import ListingId


@dataclass(frozen=True, slots=True)
class PriceChange:
    listing_id: ListingId
    from_date: date
    to_date: date
    from_amount: int
    to_amount: int

    def __post_init__(self) -> None:
        if self.from_amount <= 0:
            raise ValueError("PriceChange.from_amount must be positive")
        if self.to_amount < 0:
            raise ValueError("PriceChange.to_amount must be non-negative")
        if self.from_date > self.to_date:
            raise ValueError("PriceChange dates inverted: from_date > to_date")

    @property
    def delta_amount(self) -> int:
        return self.to_amount - self.from_amount

    @property
    def delta_pct(self) -> float:
        return (self.delta_amount / self.from_amount) * 100.0

    @property
    def is_drop(self) -> bool:
        return self.delta_amount < 0
